; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_feather_esp32_v2]
platform = espressif32
board = esp32dev
framework = arduino

; Ensure correct flash size
board_build.flash_size = 4MB

; Serial monitor baud rate
monitor_speed = 115200

; Library dependencies
lib_deps =
    LiquidCrystal_I2C
    MFRC522
    RTC
    makuna/RTC

; Ensure correct SPI implementation
build_flags = 
    -DSPI_MOSI=23
    -DSPI_MISO=19
    -DSPI_SCK=18
    -DSPI_SS=5

